//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Revisions = new HashSet<Revision>();
        }
    
        public int ArticleID { get; set; }
        public string Title { get; set; }
        public string Article1 { get; set; }
        public long ReadNumber { get; set; }
        public int AuthorID { get; set; }
        public string Summary { get; set; }
        public System.DateTime Date { get; set; }
        public string Keywords { get; set; }
        public string CoverPhoto { get; set; }
        public int CategoryID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Privacy { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revision> Revisions { get; set; }
    }
}
