//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles_V
    {
        public int ArticleID { get; set; }
        public int AuthorID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public System.DateTime Date { get; set; }
        public string Summary { get; set; }
        public long ReadNumber { get; set; }
        public string CoverPhoto { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Privacy { get; set; }
        public Nullable<int> AuthorityLevel { get; set; }
        public string ProfilePicture { get; set; }
    }
}
