//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files_V
    {
        public int FileID { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public string FilePath { get; set; }
        public string FileDescription { get; set; }
        public string FileHash { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ProfilePicture { get; set; }
        public int CrudAuthorID { get; set; }
        public int Crud { get; set; }
        public System.DateTime Date { get; set; }
        public int FolderID { get; set; }
        public int ParentFolderID { get; set; }
        public string FolderName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FolderFileTypes { get; set; }
        public int AuthorID { get; set; }
    }
}
