//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media_V
    {
        public int MediaID { get; set; }
        public int ParentMediaID { get; set; }
        public string FolderName { get; set; }
        public string FolderDescription { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FolderFileTypes { get; set; }
        public int AuthorID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
        public string ProfilePicture { get; set; }
    }
}
