//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revisions_V
    {
        public int RevisionID { get; set; }
        public System.DateTime Date { get; set; }
        public int ArticleID { get; set; }
        public string Title { get; set; }
    }
}
