//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_V
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<int> AuthorityLevel { get; set; }
        public int AuthorID { get; set; }
        public string LevelName { get; set; }
    }
}
